parameters:
  name: ''
  azureSubscription: 'DemoSubscription'
  baseAppName: ''
  environment: 'dev'
  location: 'eastus'

steps:
- script: echo "$baseAppName-rg"
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: $(azureSubscription)
    action: "Create Or Update Resource Group"
    resourceGroupName: $[format('{0}-{1}-rg', baseAppName, environment)]
    location: $(location)
    templateLocation: 'Linked Artifact'
    csmFile: 'src/main/az/azuredeploy.json'
    csmParametersFile: 'src/main/az/azuredeploy.json'
    overrideParameters: '-baseName $[baseAppName]-$[environment]'